name: "Nightly build"
on:
  schedule:
    - cron: "0 3 * * *"

  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_PERSONAL_TOKEN }}
          ref: development

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Bump versions
        run: python3 bumpversion.py nightly

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm ci --no-optional

      - name: Build production files
        run: npm run build --production

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: robotcoralci
          password: ${{ secrets.CI_PERSONAL_TOKEN }}

      - name: Build and push to Docker registries
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
          file: ./Dockerfile
          push: true
          tags: |
            robotcoral/coral-app:nightly
            ghcr.io/robotcoral/coral-app:nightly

      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.DEPLOY_NIGHTLY_WEBHOOK }}
          webhook_secret: ${{ secrets.DEPLOY_NIGHTLY_SECRET }}
          silent: true
