name: CI

on: push

jobs:
  prettify:
    runs-on: ubuntu-latest
    if: ${{ secrets.CI_PERSONAL_TOKEN}}

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_PERSONAL_TOKEN }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.PRIVATE_KEY_CI }}
          passphrase: ${{ secrets.PASSWORD_KEY_CI }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install node dependencies
        run: npm ci

      - name: Run Prettier
        run: npx prettier --write .

      - name: Commit changes
        run: |
          git config --global user.name 'robotcoralci'
          git config --global user.email 'robotcoralci@users.noreply.github.com'
          git add -A
          if [ "$(git diff --name-only --cached)" ]; then git commit -S -m "chore: run Prettier"; fi          
          git push

  run-angular-tests:
    runs-on: ubuntu-latest
    needs: [prettify]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup
        run: npm ci --no-optional --debug

      - name: Build
        run: npm run build

      - name: Test
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
