name: Test

on: push

env:
  SECRETS_AVAILABLE: ${{ secrets.CI_PERSONAL_TOKEN != '' }}

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ env.SECRETS_AVAILABLE == 'true' }}

    steps:
      - name: echo hello world
        run: echo "Hello World!"
